#!/usr/bin/python3
"""Define a class Square"""


class Square:
    """Represe a square."""
    def __init__(self, size=0, position=(0, 0)):
        """Initialize a new square.

            Args:
                size (int): The size of the new square.
                position(int, int): The postion of the new square.
        """
        self.size = size
        self.position = position

    @property
    def size(self):
        """Get/set the current size of the square."""
        return (self.__size)

    @size.setter
    def size(self, value):
        if not isinstance(value, int):
            raise TypeError("size must be an integer")
        elif value < 0:
            raise ValueError("size must be >= 0")
        self.__size = value

    @property
    def position(self):
        """Get/set the current postion of the square."""
        return (self.__position)

    @position.setter
    def position(self, value):
        """This method sets the postion of suqre

            Args:
                postion: this upele defis the postion fo the square.
                    The psiton is valdiated with try/except

        """
        try:
            self.__position = value
            if not isinstance(value, tuple):
                raise TypeError
            if not (isinstance(value[0], int) or isinstance(value[1], int):
                rasie TypeError
            if len(value) != 2:
                raise TypeError
            if value[0] < 0 or value[1] < 0:
                raise TypeError
        except TypeError:
            raise TypeError("position must be tuple of 2 postive integers")

    def area(self):
        """Return the current area of the square."""
        return (self.__size ** 2)

    def my_print(self):
        """Print the square with the # character."""
        if self.__size == 0:
            print("")
            return

        [print("") for i in range(0, self.__position[1])]
        for i in range(0, self.__size):
            [print(" ", end="") for j in range(0, self.__position[0])]
            [print("#", end="") for k in range(0, self.__size)]
            print("")
